import logging
import re
from typing import Any, List, Tuple
from app.schemas import (
    AssumptionItem,
    BeliefsResponse,
    CategorizedQuestion,
    CheckinPlan,
    CheckinResponse,
    ExperimentResponse,
    GuardrailValidationResult,
    QuestionsResponse,
    ReflectResponse,
    ReflectiveQuestionItem,
    TwoHourExperiment,
)

logger = logging.getLogger(__name__)

# Directives, advice, value judgments, and recommendation patterns to reject
DIRECTIVE_PATTERNS = [
    r"\byou should\b",
    r"\byou shouldn't\b",
    r"\byou should not\b",
    r"\bi recommend\b",
    r"\bi would recommend\b",
    r"\bwe recommend\b",
    r"\bmy recommendation\b",
    r"\bmy advice\b",
    r"\bworth it\b",
    r"\bnot worth it\b",
    r"\bdon't learn\b",
    r"\bdo not learn\b",
    r"\byou must\b",
    r"\byou ought to\b",
    r"\byou have to\b",
    r"\byou need to\b",
    r"\bthe best choice is\b",
    r"\bthe right decision is\b",
    r"\bthe correct choice is\b",
    r"\bi advise\b",
    r"\bi suggest that you\b",
    r"\bi suggest you\b",
    r"\bdefinitely learn\b",
    r"\bskip learning\b",
    r"\bgive up on\b",
    r"\bgo ahead and learn\b",
    r"\byou will regret\b",
    r"\byou won't regret\b",
    r"\byou ought\b",
]

COMPILED_DIRECTIVE_REGEX = [
    re.compile(pattern, re.IGNORECASE) for pattern in DIRECTIVE_PATTERNS
]


def extract_all_text(data: Any) -> str:
    """Recursively extracts all strings from a Pydantic model or dict/list for inspection."""
    if isinstance(data, str):
        return data
    if hasattr(data, "model_dump"):
        data = data.model_dump()
    if isinstance(data, dict):
        return " ".join(extract_all_text(v) for v in data.values())
    if isinstance(data, list):
        return " ".join(extract_all_text(item) for item in data)
    return str(data) if data is not None else ""


def regex_prefilter(content: Any) -> Tuple[bool, List[str]]:
    """
    Scans content against directive and recommendation regex patterns.
    Returns (True, []) if content passes (no forbidden patterns found),
    or (False, matched_phrases) if violations are detected.
    """
    text = extract_all_text(content)
    violations: List[str] = []

    for compiled_regex in COMPILED_DIRECTIVE_REGEX:
        matches = compiled_regex.findall(text)
        if matches:
            violations.extend(matches)

    if violations:
        logger.warning(f"Guardrail regex pre-filter detected violations: {violations}")
        return False, list(set(violations))

    return True, []


def get_fallback_beliefs(skill: str) -> BeliefsResponse:
    """Safe fallback response for /api/beliefs if generation violates guardrails."""
    return BeliefsResponse(
        skill=skill,
        assumptions=[
            AssumptionItem(
                id="A1",
                statement=f"Learning {skill} is essential to unlocking your next career milestone.",
                tag="Career Expectation",
                counter_perspective=f"What if your current skills are sufficient and {skill} is only one of multiple possible routes?",
            ),
            AssumptionItem(
                id="A2",
                statement="The time required to reach practical proficiency will detract from other high-priority pursuits.",
                tag="Opportunity Cost",
                counter_perspective="How does the cost of spending a few hours of exploratory study compare to ongoing hesitation?",
            ),
            AssumptionItem(
                id="A3",
                statement="You assume comprehensive mastery is required rather than learning targeted, lightweight concepts.",
                tag="Skill Identity",
                counter_perspective="What would be the value of knowing just enough to communicate with specialists?",
            ),
            AssumptionItem(
                id="A4",
                statement="Current industry conversations around this skill indicate an urgent necessity for your personal roadmap.",
                tag="Market Pressure",
                counter_perspective="Is this urgency generated by external industry signals or an immediate project demand you face today?",
            ),
        ],
        thinking_summary=f"Your hesitation around {skill} reflects an examination of time allocation versus anticipated career utility.",
    )


def get_fallback_questions(skill: str) -> QuestionsResponse:
    """Safe fallback response for /api/questions if generation violates guardrails."""
    return QuestionsResponse(
        skill=skill,
        questions=[
            CategorizedQuestion(
                category="goal",
                question=f"What specific problem or project would learning {skill} solve that cannot be solved with your current toolset?",
                reasoning="Distinguishes between a concrete functional need and general curiosity.",
                related_assumption_tag="Career Expectation",
            ),
            CategorizedQuestion(
                category="deadline",
                question="Is there an explicit, non-negotiable date by which you plan to apply this skill, or is the timeline self-directed?",
                reasoning="Clarifies whether urgency is artificial or externally mandated.",
                related_assumption_tag="Time Investment",
            ),
            CategorizedQuestion(
                category="trade-offs",
                question=f"What existing project, leisure activity, or skill development will you deprioritize to create hours for {skill}?",
                reasoning="Examines the real-world opportunity cost of dedicating study hours.",
                related_assumption_tag="Opportunity Cost",
            ),
            CategorizedQuestion(
                category="transferable_skills",
                question=f"Which mental models or foundations from your past experience can carry over directly into learning {skill}?",
                reasoning="Assesses the true learning slope based on existing transferable knowledge.",
                related_assumption_tag="Transferability",
            ),
            CategorizedQuestion(
                category="source_of_doubt",
                question="When you imagine pausing this decision for 3 months, what feelings or concerns immediately arise?",
                reasoning="Uncovers the underlying friction point driving ongoing hesitation.",
                related_assumption_tag="Market Pressure",
            ),
        ],
    )


def get_fallback_reflect(skill: str) -> ReflectResponse:
    """Safe fallback response for /api/reflect if generation violates guardrails."""
    return ReflectResponse(
        skill=skill,
        reflective_questions=[
            ReflectiveQuestionItem(
                id="R1",
                prompt=f"If you could never display knowledge of {skill} on a resume or social profile, would you still find satisfaction in exploring it?",
                focus_area="Internal vs External Motivation",
            ),
            ReflectiveQuestionItem(
                id="R2",
                prompt=f"What is the minimum threshold of understanding in {skill} that would feel like meaningful progress to you?",
                focus_area="Definition of Mastery",
            ),
            ReflectiveQuestionItem(
                id="R3",
                prompt=f"What would happen to your current projects and goals if you decided not to learn {skill} this quarter?",
                focus_area="Cost of Inaction",
            ),
        ],
    )


def get_fallback_experiment(skill: str) -> ExperimentResponse:
    """Safe fallback response for /api/experiment if generation violates guardrails."""
    return ExperimentResponse(
        skill=skill,
        experiment=TwoHourExperiment(
            title=f"2-Hour Low-Stakes {skill} Exploration Sandbox",
            framing="This is an exploratory option to observe your personal engagement and friction, not a recommended prescription.",
            duration_minutes=120,
            step_1_setup="Spend 20 minutes getting a minimal, zero-frills environment or online sandbox ready without reading lengthy tutorials.",
            step_2_build=f"Spend 70 minutes attempting to build one tiny, self-contained demonstration or script using {skill}.",
            step_3_reflect="Spend 30 minutes writing brief notes on how you felt during the session: did the friction feel energizing or draining?",
            observation_questions=[
                "Did troubleshooting the initial syntax and setup feel interesting or deeply frustrating?",
                "Were you curious to keep going when the 2-hour timer rang, or did you feel a sense of relief?",
                "How did the actual reality of working with this skill compare to how you imagined it beforehand?",
            ],
        ),
    )


def get_fallback_checkin(skill: str) -> CheckinResponse:
    """Safe fallback response for /api/checkin if generation violates guardrails."""
    return CheckinResponse(
        skill=skill,
        checkin_plan=CheckinPlan(
            timeline="30 Days",
            reflection_prompts=[
                f"Has your interest in {skill} persisted over the past 30 days, or has it naturally faded as other priorities took over?",
                "Have you encountered a practical situation during the last month where having this skill was genuinely required?",
                "How do you feel about the decision or pause you made regarding this skill 30 days ago?",
            ],
            trigger_events=[
                "A project or role explicitly requires this capability to proceed.",
                "You find yourself repeatedly researching this topic without external prompting.",
                "You have concluded a major commitment and now have dedicated bandwidth.",
            ],
            drift_check_question=f"Was your original desire to learn {skill} driven by a temporary burst of social or industry buzz that has now settled?",
        ),
    )
